import os
Import('env')

libcosmos = env['libs']['libcosmos']
libclues = env['libs']['libclues']

tests = env.GatherSources(suffixes=['.cxx'], recursive=False)

test_env = env.Clone()
static_lib_sources = []
test_env.ConfigureForLibOrPackage('libclues', static_lib_sources)
test_env.ConfigureForLibOrPackage('libcosmos', static_lib_sources)

run_env = test_env.Clone()
if not env['use_system_pkgs']:
    run_env.ConfigureRunForLib('libcosmos')
run_env.ConfigureRunForLib('libclues')

for test in tests:

    label = '.'.join(test.split('.')[:-1])
    test_prog_key = f'test_{label}'

    test_bin = test_env.Program(test_prog_key, [test] + static_lib_sources)

    env.Alias('clues_tests', test_prog_key)

    run_test_key = f'run_clues_test_{label}'
    logfile = Dir('.').abspath + '/' + run_test_key + '.log'
    binary = test_bin[0].abspath
    test_action = run_env.Action(f'{binary} >{logfile} 2>&1 || (cat {logfile} && exit 1)')
    run_cmd = run_env.Command(f'{run_test_key}.command', test_bin, test_action)

    env.Alias(run_test_key, run_cmd)
    env.Alias('run_clues_tests', run_test_key)

# for the execve test we need a binary built using our toolchain flags to
# support e.g. builds with '-m32', which gets us a 32-bit tracer on a 64-bit
# system. A 32-bit tracer cannot (sensibly) trace a 64-bit program.
#
# we also need to filter out any sanitizer settings from the environment,
# because the sanitizer code is incompatible with being traced.
# TODO: place this logic into a common function like
# env.CloneNonSanitizerEnv()
exiter_env = test_env.Clone()

for var in ('CXXFLAGS', 'LINKFLAGS'):
    new_flags = []
    for flag in str(exiter_env[var]).split():
        if flag.startswith('-fsanitize'):
            continue
        new_flags.append(flag)
    exiter_env[var] = ' '.join(new_flags)
try:
    exiter_env['LIBS'].remove('asan')
    exiter_env['LIBS'].remove('ubsan')
except (ValueError, KeyError):
    pass
exiter = exiter_env.Program('exiter', ['helpers/exiter.cxx'] + static_lib_sources)
run_env.Requires('test_execve', exiter)

env.Alias("tests", "clues_tests")
env.Alias('run_tests', 'run_clues_tests')


def inc_test_builder(env, target, source):
    inc = str(source[0]).split('include/')[1]
    with open(str(target[0]), 'w') as fd:
        fd.write(f'#include "{str(inc)}"\n\nint main() {{ return 0; }}')


srcroot = '/'.join(Dir('.').srcnode().abspath.split('/')[:-1])
incroot = srcroot + '/include/clues'

for root, dr, fls in os.walk(incroot):
    for fl in fls:
        if not fl.endswith('.hxx'):
            continue

        path = root + '/' + fl
        idx = path.rfind('clues')
        if idx == -1:
            continue
        include = path[idx:]
        include_src = srcroot + '/include/' + include
        gensrc = include.replace('/', '_').split('.hxx')[0]
        test_env.Command(f'{gensrc}.cxx', include_src, action=inc_test_builder)
        prog = test_env.Program(f'{gensrc}_test', f'{gensrc}.cxx')

        env.Alias('include_compile_tests', prog)

env.Alias('tests', 'include_compile_tests')
