var annotated_dup =
[
    [ "clues", "namespaceclues.html", [
      [ "format", null, [
        [ "HexChar", "structclues_1_1format_1_1HexChar.html", null ]
      ] ],
      [ "item", null, [
        [ "kernel", null, [
          [ "flock64", "structclues_1_1item_1_1kernel_1_1flock64.html", null ],
          [ "flock_t", "structclues_1_1item_1_1kernel_1_1flock__t.html", null ]
        ] ],
        [ "AccessModeParameter", "classclues_1_1item_1_1AccessModeParameter.html", "classclues_1_1item_1_1AccessModeParameter" ],
        [ "AtFlagsValue", "classclues_1_1item_1_1AtFlagsValue.html", "classclues_1_1item_1_1AtFlagsValue" ],
        [ "BufferPointer", "classclues_1_1item_1_1BufferPointer.html", "classclues_1_1item_1_1BufferPointer" ],
        [ "ClockID", "classclues_1_1item_1_1ClockID.html", "classclues_1_1item_1_1ClockID" ],
        [ "ClockNanoSleepFlags", "classclues_1_1item_1_1ClockNanoSleepFlags.html", "classclues_1_1item_1_1ClockNanoSleepFlags" ],
        [ "CloneArgs", "classclues_1_1item_1_1CloneArgs.html", "classclues_1_1item_1_1CloneArgs" ],
        [ "CloneFlagsValue", "classclues_1_1item_1_1CloneFlagsValue.html", "classclues_1_1item_1_1CloneFlagsValue" ],
        [ "DirEntries", "classclues_1_1item_1_1DirEntries.html", "classclues_1_1item_1_1DirEntries" ],
        [ "DNotifySettings", "classclues_1_1item_1_1DNotifySettings.html", "classclues_1_1item_1_1DNotifySettings" ],
        [ "ExitStatusItem", "classclues_1_1item_1_1ExitStatusItem.html", "classclues_1_1item_1_1ExitStatusItem" ],
        [ "ExtFileDescOwner", "classclues_1_1item_1_1ExtFileDescOwner.html", "classclues_1_1item_1_1ExtFileDescOwner" ],
        [ "FcntlOperation", "classclues_1_1item_1_1FcntlOperation.html", "classclues_1_1item_1_1FcntlOperation" ],
        [ "FileDescFlagsValue", "structclues_1_1item_1_1FileDescFlagsValue.html", "structclues_1_1item_1_1FileDescFlagsValue" ],
        [ "FileDescOwner", "classclues_1_1item_1_1FileDescOwner.html", "classclues_1_1item_1_1FileDescOwner" ],
        [ "FileDescriptor", "classclues_1_1item_1_1FileDescriptor.html", "classclues_1_1item_1_1FileDescriptor" ],
        [ "FileModeParameter", "classclues_1_1item_1_1FileModeParameter.html", "classclues_1_1item_1_1FileModeParameter" ],
        [ "FileSealSettings", "classclues_1_1item_1_1FileSealSettings.html", "classclues_1_1item_1_1FileSealSettings" ],
        [ "FLockParameter", "classclues_1_1item_1_1FLockParameter.html", "classclues_1_1item_1_1FLockParameter" ],
        [ "FutexOperation", "classclues_1_1item_1_1FutexOperation.html", "classclues_1_1item_1_1FutexOperation" ],
        [ "FutexWakeOperation", "classclues_1_1item_1_1FutexWakeOperation.html", "classclues_1_1item_1_1FutexWakeOperation" ],
        [ "GenericPointerValue", "classclues_1_1item_1_1GenericPointerValue.html", "classclues_1_1item_1_1GenericPointerValue" ],
        [ "GroupID", "classclues_1_1item_1_1GroupID.html", "classclues_1_1item_1_1GroupID" ],
        [ "IntValueT", "classclues_1_1item_1_1IntValueT.html", "classclues_1_1item_1_1IntValueT" ],
        [ "LeaseType", "classclues_1_1item_1_1LeaseType.html", "classclues_1_1item_1_1LeaseType" ],
        [ "MapFlagsParameter", "classclues_1_1item_1_1MapFlagsParameter.html", "classclues_1_1item_1_1MapFlagsParameter" ],
        [ "MemoryProtectionParameter", "classclues_1_1item_1_1MemoryProtectionParameter.html", "classclues_1_1item_1_1MemoryProtectionParameter" ],
        [ "OldMmapArgs", "classclues_1_1item_1_1OldMmapArgs.html", "classclues_1_1item_1_1OldMmapArgs" ],
        [ "OpenFlagsValue", "classclues_1_1item_1_1OpenFlagsValue.html", "classclues_1_1item_1_1OpenFlagsValue" ],
        [ "PipeEnds", "classclues_1_1item_1_1PipeEnds.html", "classclues_1_1item_1_1PipeEnds" ],
        [ "PipeFlags", "classclues_1_1item_1_1PipeFlags.html", "classclues_1_1item_1_1PipeFlags" ],
        [ "PointerInValue", "classclues_1_1item_1_1PointerInValue.html", null ],
        [ "PointerOutValue", "classclues_1_1item_1_1PointerOutValue.html", null ],
        [ "PointerToScalar", "classclues_1_1item_1_1PointerToScalar.html", "classclues_1_1item_1_1PointerToScalar" ],
        [ "PointerValue", "classclues_1_1item_1_1PointerValue.html", null ],
        [ "ProcessIDItem", "classclues_1_1item_1_1ProcessIDItem.html", "classclues_1_1item_1_1ProcessIDItem" ],
        [ "ReadWriteHint", "classclues_1_1item_1_1ReadWriteHint.html", "classclues_1_1item_1_1ReadWriteHint" ],
        [ "ResourceLimit", "classclues_1_1item_1_1ResourceLimit.html", "classclues_1_1item_1_1ResourceLimit" ],
        [ "ResourceType", "classclues_1_1item_1_1ResourceType.html", "classclues_1_1item_1_1ResourceType" ],
        [ "ResourceUsageItem", "classclues_1_1item_1_1ResourceUsageItem.html", "classclues_1_1item_1_1ResourceUsageItem" ],
        [ "ReturnValue", "classclues_1_1item_1_1ReturnValue.html", null ],
        [ "SigActionParameter", "classclues_1_1item_1_1SigActionParameter.html", "classclues_1_1item_1_1SigActionParameter" ],
        [ "SignalNumber", "classclues_1_1item_1_1SignalNumber.html", "classclues_1_1item_1_1SignalNumber" ],
        [ "SigSetOperation", "classclues_1_1item_1_1SigSetOperation.html", "classclues_1_1item_1_1SigSetOperation" ],
        [ "SigSetParameter", "classclues_1_1item_1_1SigSetParameter.html", "classclues_1_1item_1_1SigSetParameter" ],
        [ "StatParameter", "classclues_1_1item_1_1StatParameter.html", "classclues_1_1item_1_1StatParameter" ],
        [ "StringArrayData", "classclues_1_1item_1_1StringArrayData.html", "classclues_1_1item_1_1StringArrayData" ],
        [ "StringData", "classclues_1_1item_1_1StringData.html", "classclues_1_1item_1_1StringData" ],
        [ "SuccessResult", "classclues_1_1item_1_1SuccessResult.html", "classclues_1_1item_1_1SuccessResult" ],
        [ "ThreadIDItem", "classclues_1_1item_1_1ThreadIDItem.html", "classclues_1_1item_1_1ThreadIDItem" ],
        [ "TimeSpecParameter", "classclues_1_1item_1_1TimeSpecParameter.html", "classclues_1_1item_1_1TimeSpecParameter" ],
        [ "UnknownItem", "structclues_1_1item_1_1UnknownItem.html", "structclues_1_1item_1_1UnknownItem" ],
        [ "UserID", "classclues_1_1item_1_1UserID.html", "classclues_1_1item_1_1UserID" ],
        [ "ValueInParameter", "classclues_1_1item_1_1ValueInParameter.html", null ],
        [ "ValueOutParameter", "classclues_1_1item_1_1ValueOutParameter.html", null ],
        [ "ValueParameter", "classclues_1_1item_1_1ValueParameter.html", null ],
        [ "WaitOptionsItem", "classclues_1_1item_1_1WaitOptionsItem.html", "classclues_1_1item_1_1WaitOptionsItem" ],
        [ "WaitStatusItem", "classclues_1_1item_1_1WaitStatusItem.html", "classclues_1_1item_1_1WaitStatusItem" ]
      ] ],
      [ "AccessSystemCall", "structclues_1_1AccessSystemCall.html", null ],
      [ "AlarmSystemCall", "structclues_1_1AlarmSystemCall.html", null ],
      [ "Args", "structclues_1_1Args.html", "structclues_1_1Args" ],
      [ "AutoAttachedTracee", "classclues_1_1AutoAttachedTracee.html", "classclues_1_1AutoAttachedTracee" ],
      [ "BreakSystemCall", "structclues_1_1BreakSystemCall.html", null ],
      [ "ChildTracee", "classclues_1_1ChildTracee.html", "classclues_1_1ChildTracee" ],
      [ "ClockNanoSleepSystemCall", "structclues_1_1ClockNanoSleepSystemCall.html", null ],
      [ "Clone3SystemCall", "structclues_1_1Clone3SystemCall.html", "structclues_1_1Clone3SystemCall" ],
      [ "CloneSystemCall", "structclues_1_1CloneSystemCall.html", "structclues_1_1CloneSystemCall" ],
      [ "CloseSystemCall", "structclues_1_1CloseSystemCall.html", "structclues_1_1CloseSystemCall" ],
      [ "Engine", "classclues_1_1Engine.html", "classclues_1_1Engine" ],
      [ "ErrnoResult", "classclues_1_1ErrnoResult.html", null ],
      [ "EventConsumer", "classclues_1_1EventConsumer.html", "classclues_1_1EventConsumer" ],
      [ "ExecveAtSystemCall", "structclues_1_1ExecveAtSystemCall.html", null ],
      [ "ExecveSystemCall", "structclues_1_1ExecveSystemCall.html", null ],
      [ "ExitGroupSystemCall", "structclues_1_1ExitGroupSystemCall.html", null ],
      [ "FAccessAt2SystemCall", "structclues_1_1FAccessAt2SystemCall.html", null ],
      [ "FAccessAtSystemCall", "structclues_1_1FAccessAtSystemCall.html", null ],
      [ "FcntlSystemCall", "structclues_1_1FcntlSystemCall.html", "structclues_1_1FcntlSystemCall" ],
      [ "FDInfo", "structclues_1_1FDInfo.html", "structclues_1_1FDInfo" ],
      [ "ForeignTracee", "classclues_1_1ForeignTracee.html", "classclues_1_1ForeignTracee" ],
      [ "ForkSystemCall", "structclues_1_1ForkSystemCall.html", null ],
      [ "FstatAtSystemCall", "structclues_1_1FstatAtSystemCall.html", null ],
      [ "FstatSystemCall", "structclues_1_1FstatSystemCall.html", null ],
      [ "FutexSystemCall", "structclues_1_1FutexSystemCall.html", "structclues_1_1FutexSystemCall" ],
      [ "GetDentsSystemCall", "structclues_1_1GetDentsSystemCall.html", "structclues_1_1GetDentsSystemCall" ],
      [ "GetRobustListSystemCall", "structclues_1_1GetRobustListSystemCall.html", null ],
      [ "GetXIdSystemCall", "structclues_1_1GetXIdSystemCall.html", "structclues_1_1GetXIdSystemCall" ],
      [ "IoCtlSystemCall", "structclues_1_1IoCtlSystemCall.html", null ],
      [ "kernel_old_sigaction", "structclues_1_1kernel__old__sigaction.html", null ],
      [ "kernel_sigaction", "structclues_1_1kernel__sigaction.html", "structclues_1_1kernel__sigaction" ],
      [ "kernel_sigaction32", "structclues_1_1kernel__sigaction32.html", null ],
      [ "LimitSystemCallT", "structclues_1_1LimitSystemCallT.html", null ],
      [ "linux_dirent", "structclues_1_1linux__dirent.html", null ],
      [ "linux_dirent32", "structclues_1_1linux__dirent32.html", null ],
      [ "linux_dirent64", "structclues_1_1linux__dirent64.html", null ],
      [ "mmap_arg_struct", "structclues_1_1mmap__arg__struct.html", null ],
      [ "MmapSystemCall", "structclues_1_1MmapSystemCall.html", "structclues_1_1MmapSystemCall" ],
      [ "MprotectSystemCall", "structclues_1_1MprotectSystemCall.html", null ],
      [ "MunmapSystemCall", "structclues_1_1MunmapSystemCall.html", null ],
      [ "NanoSleepSystemCall", "structclues_1_1NanoSleepSystemCall.html", null ],
      [ "old_kernel_stat", "structclues_1_1old__kernel__stat.html", null ],
      [ "OpenAtSystemCall", "structclues_1_1OpenAtSystemCall.html", "structclues_1_1OpenAtSystemCall" ],
      [ "OpenSystemCall", "structclues_1_1OpenSystemCall.html", "structclues_1_1OpenSystemCall" ],
      [ "Pipe2SystemCall", "structclues_1_1Pipe2SystemCall.html", null ],
      [ "PipeSystemCall", "structclues_1_1PipeSystemCall.html", "structclues_1_1PipeSystemCall" ],
      [ "Prlimit64SystemCall", "structclues_1_1Prlimit64SystemCall.html", null ],
      [ "ProcessData", "classclues_1_1ProcessData.html", "classclues_1_1ProcessData" ],
      [ "ReadSystemCall", "structclues_1_1ReadSystemCall.html", null ],
      [ "RegisterData", "structclues_1_1RegisterData.html", "structclues_1_1RegisterData" ],
      [ "RegisterDataAARCH64", "structclues_1_1RegisterDataAARCH64.html", null ],
      [ "RegisterDataI386", "structclues_1_1RegisterDataI386.html", "structclues_1_1RegisterDataI386" ],
      [ "RegisterDataTraits", "structclues_1_1RegisterDataTraits.html", "structclues_1_1RegisterDataTraits" ],
      [ "RegisterDataTraits< ABI::AARCH64 >", "structclues_1_1RegisterDataTraits_3_01ABI_1_1AARCH64_01_4.html", "structclues_1_1RegisterDataTraits_3_01ABI_1_1AARCH64_01_4" ],
      [ "RegisterDataTraits< ABI::I386 >", "structclues_1_1RegisterDataTraits_3_01ABI_1_1I386_01_4.html", "structclues_1_1RegisterDataTraits_3_01ABI_1_1I386_01_4" ],
      [ "RegisterDataTraits< ABI::X32 >", "structclues_1_1RegisterDataTraits_3_01ABI_1_1X32_01_4.html", "structclues_1_1RegisterDataTraits_3_01ABI_1_1X32_01_4" ],
      [ "RegisterDataTraits< ABI::X86_64 >", "structclues_1_1RegisterDataTraits_3_01ABI_1_1X86__64_01_4.html", "structclues_1_1RegisterDataTraits_3_01ABI_1_1X86__64_01_4" ],
      [ "RegisterDataX32", "structclues_1_1RegisterDataX32.html", null ],
      [ "RegisterDataX64", "structclues_1_1RegisterDataX64.html", null ],
      [ "RegisterDataX86_64_T", "structclues_1_1RegisterDataX86__64__T.html", null ],
      [ "RegisterSet", "classclues_1_1RegisterSet.html", "classclues_1_1RegisterSet" ],
      [ "RestartSystemCall", "structclues_1_1RestartSystemCall.html", null ],
      [ "rlimit32", "structclues_1_1rlimit32.html", null ],
      [ "rlimit64", "structclues_1_1rlimit64.html", null ],
      [ "RtSigActionSystemCall", "structclues_1_1RtSigActionSystemCall.html", "structclues_1_1RtSigActionSystemCall" ],
      [ "RtSigProcMaskSystemCall", "structclues_1_1RtSigProcMaskSystemCall.html", "structclues_1_1RtSigProcMaskSystemCall" ],
      [ "SetRobustListSystemCall", "structclues_1_1SetRobustListSystemCall.html", null ],
      [ "SetTIDAddressSystemCall", "structclues_1_1SetTIDAddressSystemCall.html", "structclues_1_1SetTIDAddressSystemCall" ],
      [ "SigActionSystemCall", "structclues_1_1SigActionSystemCall.html", null ],
      [ "SigProcMaskSystemCall", "structclues_1_1SigProcMaskSystemCall.html", null ],
      [ "stat32", "structclues_1_1stat32.html", null ],
      [ "stat32_64", "structclues_1_1stat32__64.html", null ],
      [ "stat64", "structclues_1_1stat64.html", null ],
      [ "StatSystemCallT", "structclues_1_1StatSystemCallT.html", null ],
      [ "SystemCall", "classclues_1_1SystemCall.html", "classclues_1_1SystemCall" ],
      [ "SystemCallDB", "classclues_1_1SystemCallDB.html", null ],
      [ "SystemCallInfo", "classclues_1_1SystemCallInfo.html", "classclues_1_1SystemCallInfo" ],
      [ "SystemCallItem", "classclues_1_1SystemCallItem.html", "classclues_1_1SystemCallItem" ],
      [ "SystemCallNrTraits", "structclues_1_1SystemCallNrTraits.html", null ],
      [ "SystemCallNrTraits< ABI::AARCH64 >", "structclues_1_1SystemCallNrTraits_3_01ABI_1_1AARCH64_01_4.html", null ],
      [ "SystemCallNrTraits< ABI::I386 >", "structclues_1_1SystemCallNrTraits_3_01ABI_1_1I386_01_4.html", null ],
      [ "SystemCallNrTraits< ABI::X32 >", "structclues_1_1SystemCallNrTraits_3_01ABI_1_1X32_01_4.html", null ],
      [ "SystemCallNrTraits< ABI::X86_64 >", "structclues_1_1SystemCallNrTraits_3_01ABI_1_1X86__64_01_4.html", null ],
      [ "TermTracer", "classclues_1_1TermTracer.html", "classclues_1_1TermTracer" ],
      [ "TgKillSystemCall", "structclues_1_1TgKillSystemCall.html", null ],
      [ "timespec32", "structclues_1_1timespec32.html", null ],
      [ "Tracee", "classclues_1_1Tracee.html", "classclues_1_1Tracee" ],
      [ "UnknownSystemCall", "structclues_1_1UnknownSystemCall.html", null ],
      [ "Wait4SystemCall", "structclues_1_1Wait4SystemCall.html", null ],
      [ "WriteSystemCall", "structclues_1_1WriteSystemCall.html", null ]
    ] ]
];