// C++
#include <format>

// cosmos
#include <cosmos/utils.hxx>

// clues
#include <clues/items/caps.hxx>
#include <clues/macros.h>

namespace clues::item {

std::string Capability::str() const {
	const auto raw_cap = cosmos::to_integral(m_cap);
	switch (raw_cap) {
		CASE_ENUM_TO_STR(CAP_CHOWN);
		CASE_ENUM_TO_STR(CAP_DAC_OVERRIDE);
		CASE_ENUM_TO_STR(CAP_DAC_READ_SEARCH);
		CASE_ENUM_TO_STR(CAP_FOWNER);
		CASE_ENUM_TO_STR(CAP_FSETID);
		CASE_ENUM_TO_STR(CAP_KILL);
		CASE_ENUM_TO_STR(CAP_SETGID);
		CASE_ENUM_TO_STR(CAP_SETUID);
		CASE_ENUM_TO_STR(CAP_SETPCAP);
		CASE_ENUM_TO_STR(CAP_LINUX_IMMUTABLE);
		CASE_ENUM_TO_STR(CAP_NET_BIND_SERVICE);
		CASE_ENUM_TO_STR(CAP_NET_BROADCAST);
		CASE_ENUM_TO_STR(CAP_NET_ADMIN);
		CASE_ENUM_TO_STR(CAP_NET_RAW);
		CASE_ENUM_TO_STR(CAP_IPC_LOCK);
		CASE_ENUM_TO_STR(CAP_IPC_OWNER);
		CASE_ENUM_TO_STR(CAP_SYS_MODULE);
		CASE_ENUM_TO_STR(CAP_SYS_RAWIO);
		CASE_ENUM_TO_STR(CAP_SYS_CHROOT);
		CASE_ENUM_TO_STR(CAP_SYS_PTRACE);
		CASE_ENUM_TO_STR(CAP_SYS_PACCT);
		CASE_ENUM_TO_STR(CAP_SYS_ADMIN);
		CASE_ENUM_TO_STR(CAP_SYS_BOOT);
		CASE_ENUM_TO_STR(CAP_SYS_NICE);
		CASE_ENUM_TO_STR(CAP_SYS_RESOURCE);
		CASE_ENUM_TO_STR(CAP_SYS_TIME);
		CASE_ENUM_TO_STR(CAP_SYS_TTY_CONFIG);
		CASE_ENUM_TO_STR(CAP_MKNOD);
		CASE_ENUM_TO_STR(CAP_LEASE);
		CASE_ENUM_TO_STR(CAP_AUDIT_WRITE);
		CASE_ENUM_TO_STR(CAP_AUDIT_CONTROL);
		CASE_ENUM_TO_STR(CAP_SETFCAP);
		CASE_ENUM_TO_STR(CAP_MAC_OVERRIDE);
		CASE_ENUM_TO_STR(CAP_MAC_ADMIN);
		CASE_ENUM_TO_STR(CAP_SYSLOG);
		CASE_ENUM_TO_STR(CAP_WAKE_ALARM);
		CASE_ENUM_TO_STR(CAP_BLOCK_SUSPEND);
		CASE_ENUM_TO_STR(CAP_AUDIT_READ);
		CASE_ENUM_TO_STR(CAP_PERFMON);
		CASE_ENUM_TO_STR(CAP_BPF);
		CASE_ENUM_TO_STR(CAP_CHECKPOINT_RESTORE);
		default: return std::format("{} (CAP_\?\?\?)", raw_cap);
	}
}

void Capability::processValue(const Tracee&) {
	m_cap = cosmos::Capability{valueAs<long>()};
}

} // end ns
