Import('env')

if not env['build_docs']:
    Return()

doc_env = env.Clone()

states_cmd = doc_env.Command(
    '#doc/states.pdf',
    'states.gv',
    action='dot -Tpdf $SOURCE -o $TARGET')
env.Alias('states_graph', states_cmd)

doxy_cmd = doc_env.Command(
    'doxygen/html/index.html',
    'doxygen.conf',
    action='doxygen -q $SOURCE')
env.AlwaysBuild(doxy_cmd)
env.Alias('doxygen', doxy_cmd)
