Import('env')

libcosmos = env['libs']['libcosmos']

tests = (
	"exceptions",
	"pipe",
	"subproc",
	"thread_primitives",
	"dirs"
)

for test in tests:

	test_bin = env.Program(
		"test_{}".format(test),
		["{}.cxx".format(test), libcosmos]
	)

	env.Alias("cosmos_tests", test_bin)

env.Alias("tests", "cosmos_tests")
