Import('env')

# for the execve test we need a binary built using our toolchain flags to
# support e.g. builds with '-m32', which gets us a 32-bit tracer on a 64-bit
# system. A 32-bit tracer cannot (sensibly) trace a 64-bit program.
#
# We also need to filter out any sanitizer settings from the environment,
# because the sanitizer code is incompatible with being traced.
env = env.CloneNoSanitizer()

env['helpers'] = {}
static_sources = []
env.ConfigureForLibOrPackage('libcosmos', static_sources)

for helper in env.GatherSources(suffixes=['.cxx']):
    label = '.'.join(helper.split('.')[:-1])
    exe = helper.rsplit('.', 1)[0]
    node = env.Program(exe, [helper] + static_sources)

    env['helpers'][label] = node
    key = f'helper_{label}'
    env.Alias(key, node)
    env.Alias("test_helpers", node)

Return('env')
