Import('test_env')

env = test_env

# for the execve test we need a binary built using our toolchain flags to
# support e.g. builds with '-m32', which gets us a 32-bit tracer on a 64-bit
# system. A 32-bit tracer cannot (sensibly) trace a 64-bit program.
#
# we also need to filter out any sanitizer settings from the environment,
# because the sanitizer code is incompatible with being traced.
# TODO: place this logic into a common function like
# env.CloneNonSanitizerEnv()
helper_env = env.Clone()

for var in ('CXXFLAGS', 'LINKFLAGS'):
    new_flags = []
    for flag in str(helper_env[var]).split():
        if flag.startswith('-fsanitize'):
            continue
        new_flags.append(flag)
    helper_env[var] = ' '.join(new_flags)
try:
    helper_env['LIBS'].remove('asan')
    helper_env['LIBS'].remove('ubsan')
except (ValueError, KeyError):
    pass

static_lib_sources = env['static_lib_sources']
env['helpers'] = {}

for helper in env.GatherSources(suffixes=['.cxx']):
    label = '.'.join(helper.split('.')[:-1])
    exe = helper.rsplit('.', 1)[0]
    node = helper_env.Program(exe, [helper] + static_lib_sources)

    env['helpers'][label] = node
    key = f'helper_{label}'
    helper_env.Alias(key, node)
    helper_env.Alias("test_helpers", node)

Return('env')
