Import('env')

lib_srcs = [
	"TracedProc.cxx",
	"TracedThread.cxx",
	"SubProc.cxx",
	"errors/ApiError.cxx",
	"errors/CluesError.cxx",
	"types.cxx",
	"WaitRes.cxx",
	"Signal.cxx",
	"SystemCall.cxx",
	"SystemCallDB.cxx",
	"Parameters.cxx"
]

tracer_srcs = [
	"TermTracer.cxx",
]

tracelib = env.SharedLibrary(
	"clues",
	lib_srcs
)

clues = env.Program(
	"clues",
	tracer_srcs + [tracelib]
)

env['libs']['clues'] = tracelib
