Import('env')


def buildErrnosHeader(target, source, env):
    import subprocess
    cmdline = [env["CC"], "-E", "-dD", str(source[0])]
    output = subprocess.check_output(cmdline)
    output = output.decode('utf8')

    errnos = [(0, "EOK")]

    for line in output.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split(None)
        if len(parts) != 3:
            continue

        define, name, value = parts
        if define != "#define":
            continue
        elif not name.startswith('E'):
            continue
        elif not value.isnumeric():
            continue

        has_lower = False
        for ch in name:
            if not ch.isupper():
                has_lower = True
                break
        if has_lower:
            continue

        errnos.append((int(value), name))

    max_errno = max([errno[0] for errno in errnos])
    all_errnos = set([errno[0] for errno in errnos])

    for errno in range(max_errno):
        if errno not in all_errnos:
            errnos.append((errno, "E{}".format(str(errno))))

    errnos.sort()

    with open(str(target[0]), 'w') as out_fd:
        out_fd.write("#pragma once\n\n")
        out_fd.write("#include <array>\n\n")
        out_fd.write("constexpr size_t ERRNO_NAMES_COUNT = {};\n".format(len(errnos)))
        out_fd.write("constexpr std::array<const char* const, ERRNO_NAMES_COUNT> ERRNO_NAMES = {\n")
        for nr, name in errnos:
            out_fd.write('\t"{}"'.format(name))
            if nr != len(errnos) - 1:
                out_fd.write(",")
            out_fd.write("\n")
        out_fd.write("};\n")

    return 0


errnoHeaderBuilder = env.Builder(action=buildErrnosHeader, suffix='.h', src_suffix='.c')
env.Append(BUILDERS={'ErrnoHeaderBuilder': errnoHeaderBuilder})


def buildSyscallHeader(target, source, env):
    import subprocess
    cflags = str(env.get("CCFLAGS"))
    cflags = cflags.split() if cflags else []
    cmdline = [env["CC"]] + cflags + ["-E", "-dD", str(source[0])]
    output = subprocess.check_output(cmdline)
    output = output.decode('utf8')

    syscalls = {}
    numbers = {}
    max_number = 0

    for line in output.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split(None)
        if len(parts) != 3:
            continue

        define, name, value = parts
        if define != "#define":
            continue
        elif name.startswith('SYS_') and value.startswith('__NR_'):
            syscalls[value] = name
        elif name.startswith('__NR_') and value.isnumeric():
            number = int(value)
            numbers[number] = name
            max_number = max(max_number, number)

    with open(str(target[0]), 'w') as out_fd:
        out_fd.write("#pragma once\n")
        out_fd.write("#include <stdlib.h>\n")
        out_fd.write("#include <elf.h>\n")
        out_fd.write("#include <sys/syscall.h>\n\n")
        out_fd.write("#include <array>\n")
        out_fd.write("#include <map>\n")
        out_fd.write("#include <string_view>\n")
        out_fd.write("\n// C++ class enum for system call numbers found in syscall.h\n")
        out_fd.write("namespace clues {\n")
        out_fd.write("enum class SystemCallNr : uint64_t {\n")
        for syscall in syscalls.values():
            _, base = syscall.split('_', 1)
            out_fd.write(f'\t{base.upper()} = {syscall},\n')
        out_fd.write("};\n\n")
        out_fd.write(f"constexpr size_t SYSTEM_CALL_COUNT = {max_number};\n\n")
        out_fd.write("constexpr std::array<const char* const, SYSTEM_CALL_COUNT> SYSTEM_CALL_NAMES = {\n")
        for nr in range(max_number):
            number_str = numbers.get(nr, None)
            label = syscalls.get(number_str, "").lstrip("SYS_")
            out_fd.write(f'\t"{label}",\n')
        out_fd.write("};\n")
        out_fd.write("const std::map<std::string_view, SystemCallNr> SYSTEM_CALL_NAME_MAP = {\n")
        for nr, name in syscalls.items():
            # strip the leading SYS_
            name = name.split('_', 1)[1]
            enum = name.upper()
            out_fd.write("\t{" + f"std::string_view{{\"{name}\"}}" + ", " + f"SystemCallNr::{enum}" + "},\n")
        out_fd.write("};")
        out_fd.write("\n\n} // end ns\n")

    return 0


# this header is only needed in the implementation and does not need to be
# installed as a public header
_ = env.ErrnoHeaderBuilder("clues/errnodb.hxx", "generated/errnodb.cxx")

libenv = env.Clone()
public_includes = Dir('.').srcnode().abspath + '/../include'
libenv.Append(CCFLAGS=['-include', 'clues/dso_export.h'])
libenv.Append(CPPPATH=public_includes)
# for finding private includes
libenv.Append(CPPPATH=["."])

libclues_srcs = libenv.GatherSources(suffixes=['.cxx', '.c'], recursive=False)
items_srcs = libenv.GatherSources(suffixes=['.cxx', '.c'], subpath="items")
sysnr_srcs = libenv.GatherSources(suffixes=['.cxx', '.c'], subpath="sysnrs")
libclues_srcs += items_srcs
libclues_srcs += sysnr_srcs
libenv.ConfigureForLibOrPackage('libcosmos', libclues_srcs)

version, soname, tag = libenv.GetSharedLibVersionInfo('libclues')
libenv.AddVersionFileTarget('libclues', tag)

if env['libtype'] == 'static':
    libclues = libenv.StaticLibrary(
        'clues',
        libclues_srcs
    )
else:

    libenv.Append(CCFLAGS='-fvisibility=hidden')
    libenv.Append(CCFLAGS='-DCLUES_EXPORT')

    # the SONAME and SHLIBVERSION are the knobs to tune for ABI versioning, but
    # libclues currently doesn't really have a concept for that.
    #
    # For packaging you can consider using an SONAME matching the exact library
    # release version resulting in a new ABI for each release. This at least
    # avoids inconsistencies, but breaks application that aren't rebuild against
    # the new lib version.

    libclues = libenv.SharedLibrary(
        'clues',
        libclues_srcs,
        SHLIBVERSION=version,
        SONAME=soname
    )

env.RegisterLibConfig(
    'libclues',
    libclues,
    {
        'CCFLAGS': ['-DCLUES_API='],
        'CPPPATH': [public_includes, Dir(".").abspath]
    },
    {
        'version': version
    }
)

tracer_env = env.Clone()
tracer_srcs = tracer_env.GatherSources(suffixes=['.cxx'], recursive=False, subpath='termtracer')
tracer_env.ConfigureForLibOrPackage('libclues', tracer_srcs)
tracer_env.ConfigureForLibOrPackage('libcosmos', tracer_srcs)
tracer_env.Append(CPPPATH=['#/tclap/include'])

clues = tracer_env.Program("termtracer/clues", tracer_srcs)

env['bins']['clues'] = clues
env.Alias("clues", clues)

Return('env')
