#pragma once

#include <variant>

#include "fwd.hxx"


/********************************************************************************
 * this file was generated by parse_syscall_tables.py
 * based on Linux kernel sources 6.12.31-gentoo
 ********************************************************************************/

namespace clues {

using AnySystemCallNr = std::variant<SystemCallNrI386, SystemCallNrX64, SystemCallNrX32, SystemCallNrAARCH64>;

} // end ns
