#pragma once

#include <variant>

#include "fwd.hxx"
#include <clues/types.hxx>


/********************************************************************************
 * this file was generated by parse_syscall_tables.py
 * based on Linux kernel sources 6.18.18-gentoo
 ********************************************************************************/

namespace clues {

using AnySystemCallNr = std::variant<SystemCallNrI386, SystemCallNrX64, SystemCallNrX32, SystemCallNrAARCH64>;

/// Traits which allow to lookup the correct SystemCallNr type per ABI
template <ABI abi>
struct SystemCallNrTraits {
	static_assert(abi == ABI{-1}, "no traits defined for this ABI yet");
};

template <>
struct SystemCallNrTraits<ABI::I386> {
	using type = SystemCallNrI386;
	size_t NUM_SYSCALLS = 459;
};

template <>
struct SystemCallNrTraits<ABI::X86_64> {
	using type = SystemCallNrX64;
	size_t NUM_SYSCALLS = 383;
};

template <>
struct SystemCallNrTraits<ABI::X32> {
	using type = SystemCallNrX32;
	size_t NUM_SYSCALLS = 372;
};

template <>
struct SystemCallNrTraits<ABI::AARCH64> {
	using type = SystemCallNrAARCH64;
	size_t NUM_SYSCALLS = 325;
};

} // end ns
