#pragma once

#include <stdint.h>

#include <clues/dso_export.h>


#include "fwd.hxx"


/********************************************************************************
 * this file was generated by parse_syscall_tables.py
 * based on Linux kernel sources 6.18.18-gentoo
 ********************************************************************************/

/**
 * This ABI is based on the AMD64 instruction set but uses only 32-bit pointers
 * and integers to reduce memory footprint.
 * 
 * The system call numbers have a high bit set to indicate the X32 ABI, which
 * means that the system call numbers reported by ptrace() don't directly
 * correspond to the values seen here.
 **/

namespace clues {

/// Native system call numbers as used by Linux on the x32 ABI.
/**
 * This strong enum type represents a system call number on the x32 ABI.
 * The literal values correspond to the numbers used by the operating
 * system and reported by the ptrace() API for this ABI.
 *
 * The underlying data type corresponds to the type used in the
 * `PTRACE_GET_SYSCALL_INFO` API and is the same for all ABIs.
 **/

/// This bit is set for all X32 system call to identify this ABI
constexpr uint64_t X32_SYSCALL_BIT = 0x40000000;

enum class SystemCallNrX32 : uint64_t {
	_FIRST                   = X32_SYSCALL_BIT + 0, // first valid system call nr.
	READ                     = X32_SYSCALL_BIT + 0, // common between x64 and x32
	WRITE                    = X32_SYSCALL_BIT + 1, // common between x64 and x32
	OPEN                     = X32_SYSCALL_BIT + 2, // common between x64 and x32
	CLOSE                    = X32_SYSCALL_BIT + 3, // common between x64 and x32
	STAT                     = X32_SYSCALL_BIT + 4, // common between x64 and x32
	FSTAT                    = X32_SYSCALL_BIT + 5, // common between x64 and x32
	LSTAT                    = X32_SYSCALL_BIT + 6, // common between x64 and x32
	POLL                     = X32_SYSCALL_BIT + 7, // common between x64 and x32
	LSEEK                    = X32_SYSCALL_BIT + 8, // common between x64 and x32
	MMAP                     = X32_SYSCALL_BIT + 9, // common between x64 and x32
	MPROTECT                 = X32_SYSCALL_BIT + 10, // common between x64 and x32
	MUNMAP                   = X32_SYSCALL_BIT + 11, // common between x64 and x32
	BRK                      = X32_SYSCALL_BIT + 12, // common between x64 and x32
	RT_SIGPROCMASK           = X32_SYSCALL_BIT + 14, // common between x64 and x32
	PREAD64                  = X32_SYSCALL_BIT + 17, // common between x64 and x32
	PWRITE64                 = X32_SYSCALL_BIT + 18, // common between x64 and x32
	ACCESS                   = X32_SYSCALL_BIT + 21, // common between x64 and x32
	PIPE                     = X32_SYSCALL_BIT + 22, // common between x64 and x32
	SELECT                   = X32_SYSCALL_BIT + 23, // common between x64 and x32
	SCHED_YIELD              = X32_SYSCALL_BIT + 24, // common between x64 and x32
	MREMAP                   = X32_SYSCALL_BIT + 25, // common between x64 and x32
	MSYNC                    = X32_SYSCALL_BIT + 26, // common between x64 and x32
	MINCORE                  = X32_SYSCALL_BIT + 27, // common between x64 and x32
	MADVISE                  = X32_SYSCALL_BIT + 28, // common between x64 and x32
	SHMGET                   = X32_SYSCALL_BIT + 29, // common between x64 and x32
	SHMAT                    = X32_SYSCALL_BIT + 30, // common between x64 and x32
	SHMCTL                   = X32_SYSCALL_BIT + 31, // common between x64 and x32
	DUP                      = X32_SYSCALL_BIT + 32, // common between x64 and x32
	DUP2                     = X32_SYSCALL_BIT + 33, // common between x64 and x32
	PAUSE                    = X32_SYSCALL_BIT + 34, // common between x64 and x32
	NANOSLEEP                = X32_SYSCALL_BIT + 35, // common between x64 and x32
	GETITIMER                = X32_SYSCALL_BIT + 36, // common between x64 and x32
	ALARM                    = X32_SYSCALL_BIT + 37, // common between x64 and x32
	SETITIMER                = X32_SYSCALL_BIT + 38, // common between x64 and x32
	GETPID                   = X32_SYSCALL_BIT + 39, // common between x64 and x32
	SENDFILE                 = X32_SYSCALL_BIT + 40, // common between x64 and x32
	SOCKET                   = X32_SYSCALL_BIT + 41, // common between x64 and x32
	CONNECT                  = X32_SYSCALL_BIT + 42, // common between x64 and x32
	ACCEPT                   = X32_SYSCALL_BIT + 43, // common between x64 and x32
	SENDTO                   = X32_SYSCALL_BIT + 44, // common between x64 and x32
	SHUTDOWN                 = X32_SYSCALL_BIT + 48, // common between x64 and x32
	BIND                     = X32_SYSCALL_BIT + 49, // common between x64 and x32
	LISTEN                   = X32_SYSCALL_BIT + 50, // common between x64 and x32
	GETSOCKNAME              = X32_SYSCALL_BIT + 51, // common between x64 and x32
	GETPEERNAME              = X32_SYSCALL_BIT + 52, // common between x64 and x32
	SOCKETPAIR               = X32_SYSCALL_BIT + 53, // common between x64 and x32
	CLONE                    = X32_SYSCALL_BIT + 56, // common between x64 and x32
	FORK                     = X32_SYSCALL_BIT + 57, // common between x64 and x32
	VFORK                    = X32_SYSCALL_BIT + 58, // common between x64 and x32
	EXIT                     = X32_SYSCALL_BIT + 60, // common between x64 and x32
	WAIT4                    = X32_SYSCALL_BIT + 61, // common between x64 and x32
	KILL                     = X32_SYSCALL_BIT + 62, // common between x64 and x32
	UNAME                    = X32_SYSCALL_BIT + 63, // common between x64 and x32
	SEMGET                   = X32_SYSCALL_BIT + 64, // common between x64 and x32
	SEMOP                    = X32_SYSCALL_BIT + 65, // common between x64 and x32
	SEMCTL                   = X32_SYSCALL_BIT + 66, // common between x64 and x32
	SHMDT                    = X32_SYSCALL_BIT + 67, // common between x64 and x32
	MSGGET                   = X32_SYSCALL_BIT + 68, // common between x64 and x32
	MSGSND                   = X32_SYSCALL_BIT + 69, // common between x64 and x32
	MSGRCV                   = X32_SYSCALL_BIT + 70, // common between x64 and x32
	MSGCTL                   = X32_SYSCALL_BIT + 71, // common between x64 and x32
	FCNTL                    = X32_SYSCALL_BIT + 72, // common between x64 and x32
	FLOCK                    = X32_SYSCALL_BIT + 73, // common between x64 and x32
	FSYNC                    = X32_SYSCALL_BIT + 74, // common between x64 and x32
	FDATASYNC                = X32_SYSCALL_BIT + 75, // common between x64 and x32
	TRUNCATE                 = X32_SYSCALL_BIT + 76, // common between x64 and x32
	FTRUNCATE                = X32_SYSCALL_BIT + 77, // common between x64 and x32
	GETDENTS                 = X32_SYSCALL_BIT + 78, // common between x64 and x32
	GETCWD                   = X32_SYSCALL_BIT + 79, // common between x64 and x32
	CHDIR                    = X32_SYSCALL_BIT + 80, // common between x64 and x32
	FCHDIR                   = X32_SYSCALL_BIT + 81, // common between x64 and x32
	RENAME                   = X32_SYSCALL_BIT + 82, // common between x64 and x32
	MKDIR                    = X32_SYSCALL_BIT + 83, // common between x64 and x32
	RMDIR                    = X32_SYSCALL_BIT + 84, // common between x64 and x32
	CREAT                    = X32_SYSCALL_BIT + 85, // common between x64 and x32
	LINK                     = X32_SYSCALL_BIT + 86, // common between x64 and x32
	UNLINK                   = X32_SYSCALL_BIT + 87, // common between x64 and x32
	SYMLINK                  = X32_SYSCALL_BIT + 88, // common between x64 and x32
	READLINK                 = X32_SYSCALL_BIT + 89, // common between x64 and x32
	CHMOD                    = X32_SYSCALL_BIT + 90, // common between x64 and x32
	FCHMOD                   = X32_SYSCALL_BIT + 91, // common between x64 and x32
	CHOWN                    = X32_SYSCALL_BIT + 92, // common between x64 and x32
	FCHOWN                   = X32_SYSCALL_BIT + 93, // common between x64 and x32
	LCHOWN                   = X32_SYSCALL_BIT + 94, // common between x64 and x32
	UMASK                    = X32_SYSCALL_BIT + 95, // common between x64 and x32
	GETTIMEOFDAY             = X32_SYSCALL_BIT + 96, // common between x64 and x32
	GETRLIMIT                = X32_SYSCALL_BIT + 97, // common between x64 and x32
	GETRUSAGE                = X32_SYSCALL_BIT + 98, // common between x64 and x32
	SYSINFO                  = X32_SYSCALL_BIT + 99, // common between x64 and x32
	TIMES                    = X32_SYSCALL_BIT + 100, // common between x64 and x32
	GETUID                   = X32_SYSCALL_BIT + 102, // common between x64 and x32
	SYSLOG                   = X32_SYSCALL_BIT + 103, // common between x64 and x32
	GETGID                   = X32_SYSCALL_BIT + 104, // common between x64 and x32
	SETUID                   = X32_SYSCALL_BIT + 105, // common between x64 and x32
	SETGID                   = X32_SYSCALL_BIT + 106, // common between x64 and x32
	GETEUID                  = X32_SYSCALL_BIT + 107, // common between x64 and x32
	GETEGID                  = X32_SYSCALL_BIT + 108, // common between x64 and x32
	SETPGID                  = X32_SYSCALL_BIT + 109, // common between x64 and x32
	GETPPID                  = X32_SYSCALL_BIT + 110, // common between x64 and x32
	GETPGRP                  = X32_SYSCALL_BIT + 111, // common between x64 and x32
	SETSID                   = X32_SYSCALL_BIT + 112, // common between x64 and x32
	SETREUID                 = X32_SYSCALL_BIT + 113, // common between x64 and x32
	SETREGID                 = X32_SYSCALL_BIT + 114, // common between x64 and x32
	GETGROUPS                = X32_SYSCALL_BIT + 115, // common between x64 and x32
	SETGROUPS                = X32_SYSCALL_BIT + 116, // common between x64 and x32
	SETRESUID                = X32_SYSCALL_BIT + 117, // common between x64 and x32
	GETRESUID                = X32_SYSCALL_BIT + 118, // common between x64 and x32
	SETRESGID                = X32_SYSCALL_BIT + 119, // common between x64 and x32
	GETRESGID                = X32_SYSCALL_BIT + 120, // common between x64 and x32
	GETPGID                  = X32_SYSCALL_BIT + 121, // common between x64 and x32
	SETFSUID                 = X32_SYSCALL_BIT + 122, // common between x64 and x32
	SETFSGID                 = X32_SYSCALL_BIT + 123, // common between x64 and x32
	GETSID                   = X32_SYSCALL_BIT + 124, // common between x64 and x32
	CAPGET                   = X32_SYSCALL_BIT + 125, // common between x64 and x32
	CAPSET                   = X32_SYSCALL_BIT + 126, // common between x64 and x32
	RT_SIGSUSPEND            = X32_SYSCALL_BIT + 130, // common between x64 and x32
	UTIME                    = X32_SYSCALL_BIT + 132, // common between x64 and x32
	MKNOD                    = X32_SYSCALL_BIT + 133, // common between x64 and x32
	PERSONALITY              = X32_SYSCALL_BIT + 135, // common between x64 and x32
	USTAT                    = X32_SYSCALL_BIT + 136, // common between x64 and x32
	STATFS                   = X32_SYSCALL_BIT + 137, // common between x64 and x32
	FSTATFS                  = X32_SYSCALL_BIT + 138, // common between x64 and x32
	SYSFS                    = X32_SYSCALL_BIT + 139, // common between x64 and x32
	GETPRIORITY              = X32_SYSCALL_BIT + 140, // common between x64 and x32
	SETPRIORITY              = X32_SYSCALL_BIT + 141, // common between x64 and x32
	SCHED_SETPARAM           = X32_SYSCALL_BIT + 142, // common between x64 and x32
	SCHED_GETPARAM           = X32_SYSCALL_BIT + 143, // common between x64 and x32
	SCHED_SETSCHEDULER       = X32_SYSCALL_BIT + 144, // common between x64 and x32
	SCHED_GETSCHEDULER       = X32_SYSCALL_BIT + 145, // common between x64 and x32
	SCHED_GET_PRIORITY_MAX   = X32_SYSCALL_BIT + 146, // common between x64 and x32
	SCHED_GET_PRIORITY_MIN   = X32_SYSCALL_BIT + 147, // common between x64 and x32
	SCHED_RR_GET_INTERVAL    = X32_SYSCALL_BIT + 148, // common between x64 and x32
	MLOCK                    = X32_SYSCALL_BIT + 149, // common between x64 and x32
	MUNLOCK                  = X32_SYSCALL_BIT + 150, // common between x64 and x32
	MLOCKALL                 = X32_SYSCALL_BIT + 151, // common between x64 and x32
	MUNLOCKALL               = X32_SYSCALL_BIT + 152, // common between x64 and x32
	VHANGUP                  = X32_SYSCALL_BIT + 153, // common between x64 and x32
	MODIFY_LDT               = X32_SYSCALL_BIT + 154, // common between x64 and x32
	PIVOT_ROOT               = X32_SYSCALL_BIT + 155, // common between x64 and x32
	PRCTL                    = X32_SYSCALL_BIT + 157, // common between x64 and x32
	ARCH_PRCTL               = X32_SYSCALL_BIT + 158, // common between x64 and x32
	ADJTIMEX                 = X32_SYSCALL_BIT + 159, // common between x64 and x32
	SETRLIMIT                = X32_SYSCALL_BIT + 160, // common between x64 and x32
	CHROOT                   = X32_SYSCALL_BIT + 161, // common between x64 and x32
	SYNC                     = X32_SYSCALL_BIT + 162, // common between x64 and x32
	ACCT                     = X32_SYSCALL_BIT + 163, // common between x64 and x32
	SETTIMEOFDAY             = X32_SYSCALL_BIT + 164, // common between x64 and x32
	MOUNT                    = X32_SYSCALL_BIT + 165, // common between x64 and x32
	UMOUNT2                  = X32_SYSCALL_BIT + 166, // common between x64 and x32
	SWAPON                   = X32_SYSCALL_BIT + 167, // common between x64 and x32
	SWAPOFF                  = X32_SYSCALL_BIT + 168, // common between x64 and x32
	REBOOT                   = X32_SYSCALL_BIT + 169, // common between x64 and x32
	SETHOSTNAME              = X32_SYSCALL_BIT + 170, // common between x64 and x32
	SETDOMAINNAME            = X32_SYSCALL_BIT + 171, // common between x64 and x32
	IOPL                     = X32_SYSCALL_BIT + 172, // common between x64 and x32
	IOPERM                   = X32_SYSCALL_BIT + 173, // common between x64 and x32
	INIT_MODULE              = X32_SYSCALL_BIT + 175, // common between x64 and x32
	DELETE_MODULE            = X32_SYSCALL_BIT + 176, // common between x64 and x32
	QUOTACTL                 = X32_SYSCALL_BIT + 179, // common between x64 and x32
	GETPMSG                  = X32_SYSCALL_BIT + 181, // common between x64 and x32
	PUTPMSG                  = X32_SYSCALL_BIT + 182, // common between x64 and x32
	AFS_SYSCALL              = X32_SYSCALL_BIT + 183, // common between x64 and x32
	TUXCALL                  = X32_SYSCALL_BIT + 184, // common between x64 and x32
	SECURITY                 = X32_SYSCALL_BIT + 185, // common between x64 and x32
	GETTID                   = X32_SYSCALL_BIT + 186, // common between x64 and x32
	READAHEAD                = X32_SYSCALL_BIT + 187, // common between x64 and x32
	SETXATTR                 = X32_SYSCALL_BIT + 188, // common between x64 and x32
	LSETXATTR                = X32_SYSCALL_BIT + 189, // common between x64 and x32
	FSETXATTR                = X32_SYSCALL_BIT + 190, // common between x64 and x32
	GETXATTR                 = X32_SYSCALL_BIT + 191, // common between x64 and x32
	LGETXATTR                = X32_SYSCALL_BIT + 192, // common between x64 and x32
	FGETXATTR                = X32_SYSCALL_BIT + 193, // common between x64 and x32
	LISTXATTR                = X32_SYSCALL_BIT + 194, // common between x64 and x32
	LLISTXATTR               = X32_SYSCALL_BIT + 195, // common between x64 and x32
	FLISTXATTR               = X32_SYSCALL_BIT + 196, // common between x64 and x32
	REMOVEXATTR              = X32_SYSCALL_BIT + 197, // common between x64 and x32
	LREMOVEXATTR             = X32_SYSCALL_BIT + 198, // common between x64 and x32
	FREMOVEXATTR             = X32_SYSCALL_BIT + 199, // common between x64 and x32
	TKILL                    = X32_SYSCALL_BIT + 200, // common between x64 and x32
	TIME                     = X32_SYSCALL_BIT + 201, // common between x64 and x32
	FUTEX                    = X32_SYSCALL_BIT + 202, // common between x64 and x32
	SCHED_SETAFFINITY        = X32_SYSCALL_BIT + 203, // common between x64 and x32
	SCHED_GETAFFINITY        = X32_SYSCALL_BIT + 204, // common between x64 and x32
	IO_DESTROY               = X32_SYSCALL_BIT + 207, // common between x64 and x32
	IO_GETEVENTS             = X32_SYSCALL_BIT + 208, // common between x64 and x32
	IO_CANCEL                = X32_SYSCALL_BIT + 210, // common between x64 and x32
	LOOKUP_DCOOKIE           = X32_SYSCALL_BIT + 212, // common between x64 and x32
	EPOLL_CREATE             = X32_SYSCALL_BIT + 213, // common between x64 and x32
	REMAP_FILE_PAGES         = X32_SYSCALL_BIT + 216, // common between x64 and x32
	GETDENTS64               = X32_SYSCALL_BIT + 217, // common between x64 and x32
	SET_TID_ADDRESS          = X32_SYSCALL_BIT + 218, // common between x64 and x32
	RESTART_SYSCALL          = X32_SYSCALL_BIT + 219, // common between x64 and x32
	SEMTIMEDOP               = X32_SYSCALL_BIT + 220, // common between x64 and x32
	FADVISE64                = X32_SYSCALL_BIT + 221, // common between x64 and x32
	TIMER_SETTIME            = X32_SYSCALL_BIT + 223, // common between x64 and x32
	TIMER_GETTIME            = X32_SYSCALL_BIT + 224, // common between x64 and x32
	TIMER_GETOVERRUN         = X32_SYSCALL_BIT + 225, // common between x64 and x32
	TIMER_DELETE             = X32_SYSCALL_BIT + 226, // common between x64 and x32
	CLOCK_SETTIME            = X32_SYSCALL_BIT + 227, // common between x64 and x32
	CLOCK_GETTIME            = X32_SYSCALL_BIT + 228, // common between x64 and x32
	CLOCK_GETRES             = X32_SYSCALL_BIT + 229, // common between x64 and x32
	CLOCK_NANOSLEEP          = X32_SYSCALL_BIT + 230, // common between x64 and x32
	EXIT_GROUP               = X32_SYSCALL_BIT + 231, // common between x64 and x32
	EPOLL_WAIT               = X32_SYSCALL_BIT + 232, // common between x64 and x32
	EPOLL_CTL                = X32_SYSCALL_BIT + 233, // common between x64 and x32
	TGKILL                   = X32_SYSCALL_BIT + 234, // common between x64 and x32
	UTIMES                   = X32_SYSCALL_BIT + 235, // common between x64 and x32
	MBIND                    = X32_SYSCALL_BIT + 237, // common between x64 and x32
	SET_MEMPOLICY            = X32_SYSCALL_BIT + 238, // common between x64 and x32
	GET_MEMPOLICY            = X32_SYSCALL_BIT + 239, // common between x64 and x32
	MQ_OPEN                  = X32_SYSCALL_BIT + 240, // common between x64 and x32
	MQ_UNLINK                = X32_SYSCALL_BIT + 241, // common between x64 and x32
	MQ_TIMEDSEND             = X32_SYSCALL_BIT + 242, // common between x64 and x32
	MQ_TIMEDRECEIVE          = X32_SYSCALL_BIT + 243, // common between x64 and x32
	MQ_GETSETATTR            = X32_SYSCALL_BIT + 245, // common between x64 and x32
	ADD_KEY                  = X32_SYSCALL_BIT + 248, // common between x64 and x32
	REQUEST_KEY              = X32_SYSCALL_BIT + 249, // common between x64 and x32
	KEYCTL                   = X32_SYSCALL_BIT + 250, // common between x64 and x32
	IOPRIO_SET               = X32_SYSCALL_BIT + 251, // common between x64 and x32
	IOPRIO_GET               = X32_SYSCALL_BIT + 252, // common between x64 and x32
	INOTIFY_INIT             = X32_SYSCALL_BIT + 253, // common between x64 and x32
	INOTIFY_ADD_WATCH        = X32_SYSCALL_BIT + 254, // common between x64 and x32
	INOTIFY_RM_WATCH         = X32_SYSCALL_BIT + 255, // common between x64 and x32
	MIGRATE_PAGES            = X32_SYSCALL_BIT + 256, // common between x64 and x32
	OPENAT                   = X32_SYSCALL_BIT + 257, // common between x64 and x32
	MKDIRAT                  = X32_SYSCALL_BIT + 258, // common between x64 and x32
	MKNODAT                  = X32_SYSCALL_BIT + 259, // common between x64 and x32
	FCHOWNAT                 = X32_SYSCALL_BIT + 260, // common between x64 and x32
	FUTIMESAT                = X32_SYSCALL_BIT + 261, // common between x64 and x32
	NEWFSTATAT               = X32_SYSCALL_BIT + 262, // common between x64 and x32
	UNLINKAT                 = X32_SYSCALL_BIT + 263, // common between x64 and x32
	RENAMEAT                 = X32_SYSCALL_BIT + 264, // common between x64 and x32
	LINKAT                   = X32_SYSCALL_BIT + 265, // common between x64 and x32
	SYMLINKAT                = X32_SYSCALL_BIT + 266, // common between x64 and x32
	READLINKAT               = X32_SYSCALL_BIT + 267, // common between x64 and x32
	FCHMODAT                 = X32_SYSCALL_BIT + 268, // common between x64 and x32
	FACCESSAT                = X32_SYSCALL_BIT + 269, // common between x64 and x32
	PSELECT6                 = X32_SYSCALL_BIT + 270, // common between x64 and x32
	PPOLL                    = X32_SYSCALL_BIT + 271, // common between x64 and x32
	UNSHARE                  = X32_SYSCALL_BIT + 272, // common between x64 and x32
	SPLICE                   = X32_SYSCALL_BIT + 275, // common between x64 and x32
	TEE                      = X32_SYSCALL_BIT + 276, // common between x64 and x32
	SYNC_FILE_RANGE          = X32_SYSCALL_BIT + 277, // common between x64 and x32
	UTIMENSAT                = X32_SYSCALL_BIT + 280, // common between x64 and x32
	EPOLL_PWAIT              = X32_SYSCALL_BIT + 281, // common between x64 and x32
	SIGNALFD                 = X32_SYSCALL_BIT + 282, // common between x64 and x32
	TIMERFD_CREATE           = X32_SYSCALL_BIT + 283, // common between x64 and x32
	EVENTFD                  = X32_SYSCALL_BIT + 284, // common between x64 and x32
	FALLOCATE                = X32_SYSCALL_BIT + 285, // common between x64 and x32
	TIMERFD_SETTIME          = X32_SYSCALL_BIT + 286, // common between x64 and x32
	TIMERFD_GETTIME          = X32_SYSCALL_BIT + 287, // common between x64 and x32
	ACCEPT4                  = X32_SYSCALL_BIT + 288, // common between x64 and x32
	SIGNALFD4                = X32_SYSCALL_BIT + 289, // common between x64 and x32
	EVENTFD2                 = X32_SYSCALL_BIT + 290, // common between x64 and x32
	EPOLL_CREATE1            = X32_SYSCALL_BIT + 291, // common between x64 and x32
	DUP3                     = X32_SYSCALL_BIT + 292, // common between x64 and x32
	PIPE2                    = X32_SYSCALL_BIT + 293, // common between x64 and x32
	INOTIFY_INIT1            = X32_SYSCALL_BIT + 294, // common between x64 and x32
	PERF_EVENT_OPEN          = X32_SYSCALL_BIT + 298, // common between x64 and x32
	FANOTIFY_INIT            = X32_SYSCALL_BIT + 300, // common between x64 and x32
	FANOTIFY_MARK            = X32_SYSCALL_BIT + 301, // common between x64 and x32
	PRLIMIT64                = X32_SYSCALL_BIT + 302, // common between x64 and x32
	NAME_TO_HANDLE_AT        = X32_SYSCALL_BIT + 303, // common between x64 and x32
	OPEN_BY_HANDLE_AT        = X32_SYSCALL_BIT + 304, // common between x64 and x32
	CLOCK_ADJTIME            = X32_SYSCALL_BIT + 305, // common between x64 and x32
	SYNCFS                   = X32_SYSCALL_BIT + 306, // common between x64 and x32
	SETNS                    = X32_SYSCALL_BIT + 308, // common between x64 and x32
	GETCPU                   = X32_SYSCALL_BIT + 309, // common between x64 and x32
	KCMP                     = X32_SYSCALL_BIT + 312, // common between x64 and x32
	FINIT_MODULE             = X32_SYSCALL_BIT + 313, // common between x64 and x32
	SCHED_SETATTR            = X32_SYSCALL_BIT + 314, // common between x64 and x32
	SCHED_GETATTR            = X32_SYSCALL_BIT + 315, // common between x64 and x32
	RENAMEAT2                = X32_SYSCALL_BIT + 316, // common between x64 and x32
	SECCOMP                  = X32_SYSCALL_BIT + 317, // common between x64 and x32
	GETRANDOM                = X32_SYSCALL_BIT + 318, // common between x64 and x32
	MEMFD_CREATE             = X32_SYSCALL_BIT + 319, // common between x64 and x32
	KEXEC_FILE_LOAD          = X32_SYSCALL_BIT + 320, // common between x64 and x32
	BPF                      = X32_SYSCALL_BIT + 321, // common between x64 and x32
	USERFAULTFD              = X32_SYSCALL_BIT + 323, // common between x64 and x32
	MEMBARRIER               = X32_SYSCALL_BIT + 324, // common between x64 and x32
	MLOCK2                   = X32_SYSCALL_BIT + 325, // common between x64 and x32
	COPY_FILE_RANGE          = X32_SYSCALL_BIT + 326, // common between x64 and x32
	PKEY_MPROTECT            = X32_SYSCALL_BIT + 329, // common between x64 and x32
	PKEY_ALLOC               = X32_SYSCALL_BIT + 330, // common between x64 and x32
	PKEY_FREE                = X32_SYSCALL_BIT + 331, // common between x64 and x32
	STATX                    = X32_SYSCALL_BIT + 332, // common between x64 and x32
	IO_PGETEVENTS            = X32_SYSCALL_BIT + 333, // common between x64 and x32
	RSEQ                     = X32_SYSCALL_BIT + 334, // common between x64 and x32
	URETPROBE                = X32_SYSCALL_BIT + 335, // common between x64 and x32
	UPROBE                   = X32_SYSCALL_BIT + 336, // common between x64 and x32
	PIDFD_SEND_SIGNAL        = X32_SYSCALL_BIT + 424, // common between x64 and x32
	IO_URING_SETUP           = X32_SYSCALL_BIT + 425, // common between x64 and x32
	IO_URING_ENTER           = X32_SYSCALL_BIT + 426, // common between x64 and x32
	IO_URING_REGISTER        = X32_SYSCALL_BIT + 427, // common between x64 and x32
	OPEN_TREE                = X32_SYSCALL_BIT + 428, // common between x64 and x32
	MOVE_MOUNT               = X32_SYSCALL_BIT + 429, // common between x64 and x32
	FSOPEN                   = X32_SYSCALL_BIT + 430, // common between x64 and x32
	FSCONFIG                 = X32_SYSCALL_BIT + 431, // common between x64 and x32
	FSMOUNT                  = X32_SYSCALL_BIT + 432, // common between x64 and x32
	FSPICK                   = X32_SYSCALL_BIT + 433, // common between x64 and x32
	PIDFD_OPEN               = X32_SYSCALL_BIT + 434, // common between x64 and x32
	CLONE3                   = X32_SYSCALL_BIT + 435, // common between x64 and x32
	CLOSE_RANGE              = X32_SYSCALL_BIT + 436, // common between x64 and x32
	OPENAT2                  = X32_SYSCALL_BIT + 437, // common between x64 and x32
	PIDFD_GETFD              = X32_SYSCALL_BIT + 438, // common between x64 and x32
	FACCESSAT2               = X32_SYSCALL_BIT + 439, // common between x64 and x32
	PROCESS_MADVISE          = X32_SYSCALL_BIT + 440, // common between x64 and x32
	EPOLL_PWAIT2             = X32_SYSCALL_BIT + 441, // common between x64 and x32
	MOUNT_SETATTR            = X32_SYSCALL_BIT + 442, // common between x64 and x32
	QUOTACTL_FD              = X32_SYSCALL_BIT + 443, // common between x64 and x32
	LANDLOCK_CREATE_RULESET  = X32_SYSCALL_BIT + 444, // common between x64 and x32
	LANDLOCK_ADD_RULE        = X32_SYSCALL_BIT + 445, // common between x64 and x32
	LANDLOCK_RESTRICT_SELF   = X32_SYSCALL_BIT + 446, // common between x64 and x32
	MEMFD_SECRET             = X32_SYSCALL_BIT + 447, // common between x64 and x32
	PROCESS_MRELEASE         = X32_SYSCALL_BIT + 448, // common between x64 and x32
	FUTEX_WAITV              = X32_SYSCALL_BIT + 449, // common between x64 and x32
	SET_MEMPOLICY_HOME_NODE  = X32_SYSCALL_BIT + 450, // common between x64 and x32
	CACHESTAT                = X32_SYSCALL_BIT + 451, // common between x64 and x32
	FCHMODAT2                = X32_SYSCALL_BIT + 452, // common between x64 and x32
	MAP_SHADOW_STACK         = X32_SYSCALL_BIT + 453, // common between x64 and x32
	_FUTEX_WAKE              = X32_SYSCALL_BIT + 454, // common between x64 and x32
	_FUTEX_WAIT              = X32_SYSCALL_BIT + 455, // common between x64 and x32
	_FUTEX_REQUEUE           = X32_SYSCALL_BIT + 456, // common between x64 and x32
	STATMOUNT                = X32_SYSCALL_BIT + 457, // common between x64 and x32
	LISTMOUNT                = X32_SYSCALL_BIT + 458, // common between x64 and x32
	LSM_GET_SELF_ATTR        = X32_SYSCALL_BIT + 459, // common between x64 and x32
	LSM_SET_SELF_ATTR        = X32_SYSCALL_BIT + 460, // common between x64 and x32
	LSM_LIST_MODULES         = X32_SYSCALL_BIT + 461, // common between x64 and x32
	MSEAL                    = X32_SYSCALL_BIT + 462, // common between x64 and x32
	SETXATTRAT               = X32_SYSCALL_BIT + 463, // common between x64 and x32
	GETXATTRAT               = X32_SYSCALL_BIT + 464, // common between x64 and x32
	LISTXATTRAT              = X32_SYSCALL_BIT + 465, // common between x64 and x32
	REMOVEXATTRAT            = X32_SYSCALL_BIT + 466, // common between x64 and x32
	OPEN_TREE_ATTR           = X32_SYSCALL_BIT + 467, // common between x64 and x32
	FILE_GETATTR             = X32_SYSCALL_BIT + 468, // common between x64 and x32
	FILE_SETATTR             = X32_SYSCALL_BIT + 469, // common between x64 and x32
	RT_SIGACTION             = X32_SYSCALL_BIT + 512, // specific to x32
	RT_SIGRETURN             = X32_SYSCALL_BIT + 513, // specific to x32
	IOCTL                    = X32_SYSCALL_BIT + 514, // specific to x32
	READV                    = X32_SYSCALL_BIT + 515, // specific to x32
	WRITEV                   = X32_SYSCALL_BIT + 516, // specific to x32
	RECVFROM                 = X32_SYSCALL_BIT + 517, // specific to x32
	SENDMSG                  = X32_SYSCALL_BIT + 518, // specific to x32
	RECVMSG                  = X32_SYSCALL_BIT + 519, // specific to x32
	EXECVE                   = X32_SYSCALL_BIT + 520, // specific to x32
	PTRACE                   = X32_SYSCALL_BIT + 521, // specific to x32
	RT_SIGPENDING            = X32_SYSCALL_BIT + 522, // specific to x32
	RT_SIGTIMEDWAIT          = X32_SYSCALL_BIT + 523, // specific to x32
	RT_SIGQUEUEINFO          = X32_SYSCALL_BIT + 524, // specific to x32
	SIGALTSTACK              = X32_SYSCALL_BIT + 525, // specific to x32
	TIMER_CREATE             = X32_SYSCALL_BIT + 526, // specific to x32
	MQ_NOTIFY                = X32_SYSCALL_BIT + 527, // specific to x32
	KEXEC_LOAD               = X32_SYSCALL_BIT + 528, // specific to x32
	WAITID                   = X32_SYSCALL_BIT + 529, // specific to x32
	SET_ROBUST_LIST          = X32_SYSCALL_BIT + 530, // specific to x32
	GET_ROBUST_LIST          = X32_SYSCALL_BIT + 531, // specific to x32
	VMSPLICE                 = X32_SYSCALL_BIT + 532, // specific to x32
	MOVE_PAGES               = X32_SYSCALL_BIT + 533, // specific to x32
	PREADV                   = X32_SYSCALL_BIT + 534, // specific to x32
	PWRITEV                  = X32_SYSCALL_BIT + 535, // specific to x32
	RT_TGSIGQUEUEINFO        = X32_SYSCALL_BIT + 536, // specific to x32
	RECVMMSG                 = X32_SYSCALL_BIT + 537, // specific to x32
	SENDMMSG                 = X32_SYSCALL_BIT + 538, // specific to x32
	PROCESS_VM_READV         = X32_SYSCALL_BIT + 539, // specific to x32
	PROCESS_VM_WRITEV        = X32_SYSCALL_BIT + 540, // specific to x32
	SETSOCKOPT               = X32_SYSCALL_BIT + 541, // specific to x32
	GETSOCKOPT               = X32_SYSCALL_BIT + 542, // specific to x32
	IO_SETUP                 = X32_SYSCALL_BIT + 543, // specific to x32
	IO_SUBMIT                = X32_SYSCALL_BIT + 544, // specific to x32
	EXECVEAT                 = X32_SYSCALL_BIT + 545, // specific to x32
	PREADV2                  = X32_SYSCALL_BIT + 546, // specific to x32
	PWRITEV2                 = X32_SYSCALL_BIT + 547, // specific to x32
	_LAST                    = X32_SYSCALL_BIT + 547, // last valid system call nr. (careful, could be used in the future by the kernel!)
};

/// Convert the native system call nr. into its generic representation.
/**
 * If there is no generic representation (e.g. because the `nr` is invalid
 * then SystemCallNr::UNKNOWN is returned.
 **/
CLUES_API clues::SystemCallNr to_generic(const SystemCallNrX32 nr);

} // end ns
